# Generated by Django 5.0.3 on 2024-05-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    def insert_default_claims_statuses(apps, schema_editor):
        claim_status = apps.get_model('claims', 'ClaimStatus')
        status_list = ["Опубликовано", "Получен ответ", "В работе", "Указан срок", "Решено", "Сообщение закрыто"]
        for s in status_list:
            cl_status = claim_status(name=s)
            cl_status.save()

    operations = [
        migrations.RunPython(insert_default_claims_statuses),
    ]
