# Generated by Django 5.0.3 on 2024-05-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_auto_20240522_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='image',
            field=models.ImageField(upload_to='uploads/claims/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claimstatus'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
