name: Django Tests Github CI

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [master]
    pull_request:
       branches: [master]

jobs:
  basic_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd homework_09/simpleblog
          python manage.py test